# Generated by Django 4.1.6 on 2026-08-13 10:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionModel',
            fields=[
                ('question_id', models.AutoField(primary_key=True, serialize=False)),
                ('question', models.TextField(verbose_name='Question')),
                ('answer', models.TextField(blank=True, null=True, verbose_name='Answers')),
                ('subject', models.CharField(max_length=100, verbose_name='Subject')),
                ('datetime_created', models.DateTimeField(default=datetime.datetime.now)),
            ],
            options={
                'db_table': 'question_answer',
            },
        ),
        migrations.CreateModel(
            name='SubjectModel',
            fields=[
                ('subject_id', models.AutoField(primary_key=True, serialize=False)),
                ('subject', models.CharField(max_length=100, verbose_name='Subject')),
                ('subject_image', models.FileField(upload_to='media', verbose_name='Photo')),
                ('datetime_created', models.DateTimeField(default=datetime.datetime.now)),
            ],
            options={
                'db_table': 'subject_details',
            },
        ),
    ]
