# Generated by Django 4.1.6 on 2026-08-13 10:03

import datetime
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TempModel',
            fields=[
                ('answer_id', models.AutoField(primary_key=True, serialize=False)),
                ('subject', models.CharField(max_length=50, verbose_name='Subject')),
                ('question', models.TextField(blank=True, null=True, verbose_name='Question')),
                ('answer', models.TextField(blank=True, null=True, verbose_name='Answer')),
                ('score', models.CharField(max_length=200, null=True)),
            ],
            options={
                'db_table': 'temp_model',
            },
        ),
        migrations.CreateModel(
            name='UserdetailsModel',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_name', models.CharField(max_length=50, verbose_name='Name')),
                ('user_email', models.CharField(blank=True, max_length=100, null=True, verbose_name='Email')),
                ('user_contact', models.BigIntegerField(verbose_name='contact')),
                ('user_password', models.CharField(max_length=100, verbose_name='Password')),
                ('student_id', models.CharField(max_length=100, verbose_name='Student ID')),
                ('user_photo', models.FileField(upload_to='media', verbose_name='Photo')),
                ('datetime_created', models.DateTimeField(default=datetime.datetime.now)),
                ('user_status', models.CharField(default='pending', max_length=50, null=True)),
            ],
            options={
                'db_table': 'user_details',
            },
        ),
        migrations.CreateModel(
            name='AnswerModel',
            fields=[
                ('answer_id', models.AutoField(primary_key=True, serialize=False)),
                ('answer_subject', models.CharField(max_length=50, verbose_name='Subject')),
                ('answer', models.TextField(blank=True, null=True, verbose_name='Answer')),
                ('score', models.IntegerField(null=True)),
                ('grade', models.CharField(max_length=100, null=True, verbose_name='Grade')),
                ('datetime_answered', models.DateTimeField(default=django.utils.timezone.now)),
                ('user_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Examinee', to='userapp.userdetailsmodel')),
            ],
            options={
                'db_table': 'user_answers',
            },
        ),
    ]
